services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Subrat@1234
      MYSQL_DATABASE: product-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  service-registry:
    build: ./Service-Registry/Service-Registry
    container_name: service-registry
    ports:
      - "8761:8761"

  api-gateway:
    build: ./Api-Gateway/Api-Gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - service-registry

  product-service:
    build: ./Product-Service/Product-Service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - service-registry

  order-service:
    build: ./order-service/order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - service-registry

  user-service:
    build: ./user-service/user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - service-registry

volumes:
  mysql_data: