spring.application.name=API-GATEWAY
server.port=2222

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
# Product Service
spring.cloud.gateway.routes[0].id=PRODUCT-SERVICE
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/product/**

# User Service
spring.cloud.gateway.routes[1].id=USER-SERVICE
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

# Order Service - Fixed the path here
spring.cloud.gateway.routes[2].id=ORDER-SERVICE
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/order/**

# Discovery settings
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true